/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Classes.Posts;
import Classes.Users;
import javax.swing.JFrame;

/**
 *
 * @author acer
 */
public class CardPost extends javax.swing.JPanel {

    /**
     * Creates new form CardPost
     */
    Posts data;
    public CardPost(Posts data) {
        this.data = data;
        initComponents();
        Users user = new Users(data.getUserId());
        title.setText(data.getTitle());
        posted.setText("Diposting oleh " + user.getName());
        content.setText("<html>" + data.getContent().replace("\n", "<br>")+ "</html>");
        comments.setText(data.totalComment() + " Comments");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        posted = new javax.swing.JLabel();
        content = new javax.swing.JLabel();
        comments = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        title.setText("Title");

        posted.setText("Diposting oleh ");

        content.setText("content");

        comments.setText("10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addComponent(posted)
                    .addComponent(content)
                    .addComponent(comments))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(posted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comments)
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        Post post = new Post(data.getId());
        post.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        post.setVisible(true);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comments;
    private javax.swing.JLabel content;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel posted;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
