/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Classes.Comments;
import Classes.Users;
import Config.Connect;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class CardComment extends javax.swing.JPanel {

    /**
     * Creates new form CardComment2
     */
    Comments data;
    public CardComment(Comments data) {
        this.data = data;
        initComponents();
        initComponents();
        Users user = new Users(data.getUserId());
        name.setText(user.getName());
        content.setText("<html>" + data.getContent().replace("\n", "<br>")+ "</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        content = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();

        name.setText("Name");

        content.setText("Content");

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addComponent(content)
                    .addComponent(Delete))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content)
                .addGap(18, 18, 18)
                .addComponent(Delete)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Apakah anda ingin menghapus postingan ini??","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
          // Saving code here
          System.out.print("Ya");
            try (Connection conn = Connect.getConnection(); Statement stmt = conn.createStatement()) {
                String deleteComment = "DELETE FROM comments WHERE id = " + data.getId();             
                int i = stmt.executeUpdate(deleteComment);
                if (i > 0) {
                    JOptionPane.showMessageDialog(null,
                    "Komentar berhasil dihapus!");
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null,
                    "Komentar ini sudah tidak tersedia!");
                    this.setVisible(false);
                }

            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JLabel content;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
