/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Posts;
import Config.Connect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import Classes.Users;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
/**
 *
 * @author acer
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    int offset = 0;
    int limit = 1;
    int user_id;
    public Profile(int id) {
        this.user_id = id;
        initComponents();
        panelPost.setLayout(new BoxLayout(panelPost, BoxLayout.Y_AXIS));
        updatePost('S',offset,limit);
        Users user = new Users(id);
        name.setText(user.getName());
        gender.setText(user.getGender());
        bio.setText(user.getBio());
        background.setText(user.getFaculty() + " - " + user.getUniversity());
        
        try (Connection conn = Connect.getConnection(); Statement stmt = conn.createStatement()) {
            String totalShare = "SELECT COUNT(*) FROM posts WHERE type = 's' AND user_id = " + user.getId();
            ResultSet rsShare = stmt.executeQuery(totalShare);
            
            while(rsShare.next()){
                totalPost.setText(String.valueOf(rsShare.getInt(1)));
            }
            
           
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        
        try (Connection conn = Connect.getConnection(); Statement stmt = conn.createStatement()) {
            String totalDis = "SELECT COUNT(*) FROM posts WHERE type = 'd' AND user_id = " + user.getId();
            ResultSet rsDiscussion = stmt.executeQuery(totalDis);
            
            while(rsDiscussion.next()){
                totalDiscussion.setText(String.valueOf(rsDiscussion.getInt(1)));
            }
           
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    
    private void updatePost(char type, int offset, int limit){
        try (Connection conn = Connect.getConnection(); Statement stmt = conn.createStatement()) {
            String query = "SELECT * FROM posts WHERE type = '" + type + "' AND user_id = '"+ this.user_id +"' ORDER BY id DESC LIMIT " + offset + "," + limit;
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                Posts post = new Posts(rs.getInt("id")); 
                CardPostUser cp = new CardPostUser(post);
                panelPost.add(cp);
                buttonMore();
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void buttonMore(){
        JButton buttonMore = new JButton();
        buttonMore.setSize(400,400);
        buttonMore.setVisible(true);
        buttonMore.setText("See More");
        buttonMore.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panelPost.remove(buttonMore);
                panelPost.revalidate();
                panelPost.repaint();
                offset++;
                updatePost('S',offset,limit);
            }
        });
        panelPost.add(buttonMore);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        totalPost = new javax.swing.JLabel();
        totalDiscussion = new javax.swing.JLabel();
        bio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        btnEditProfile = new javax.swing.JButton();
        btnAddSharing = new javax.swing.JButton();
        btnAddDiscussion = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        Sharing = new javax.swing.JLabel();
        Disussions = new javax.swing.JLabel();
        panelPost = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name.setText("Rama Nusa Bakti");

        totalPost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPost.setText("12");

        totalDiscussion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalDiscussion.setText("120");

        bio.setText("A man will die but not his idea! Happy Nation!");

        jLabel5.setText("Sharing");

        jLabel6.setText("Discussions");

        gender.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        gender.setText("Male");

        btnEditProfile.setText("Edit Profile");
        btnEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProfileActionPerformed(evt);
            }
        });

        btnAddSharing.setText("Add Sharing");
        btnAddSharing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSharingActionPerformed(evt);
            }
        });

        btnAddDiscussion.setText("Add Discussion");
        btnAddDiscussion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDiscussionActionPerformed(evt);
            }
        });

        background.setText("Faculty - University");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(name)
                                .addGap(18, 18, 18)
                                .addComponent(gender)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalDiscussion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bio)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnEditProfile)
                .addGap(18, 18, 18)
                .addComponent(btnAddSharing)
                .addGap(18, 18, 18)
                .addComponent(btnAddDiscussion)
                .addGap(0, 95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(totalPost)
                    .addComponent(totalDiscussion)
                    .addComponent(gender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(background))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditProfile)
                    .addComponent(btnAddSharing)
                    .addComponent(btnAddDiscussion))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        Sharing.setText("Sharing");
        Sharing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SharingMouseClicked(evt);
            }
        });

        Disussions.setText("Discussions");
        Disussions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisussionsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelPostLayout = new javax.swing.GroupLayout(panelPost);
        panelPost.setLayout(panelPostLayout);
        panelPostLayout.setHorizontalGroup(
            panelPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelPostLayout.setVerticalGroup(
            panelPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(Sharing)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(Disussions)
                .addGap(98, 98, 98))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sharing)
                    .addComponent(Disussions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProfileActionPerformed
        // TODO add your handling code here:
        EditProfile EP = new EditProfile();
        EP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        EP.setVisible(true);
    }//GEN-LAST:event_btnEditProfileActionPerformed

    private void btnAddDiscussionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDiscussionActionPerformed
        // TODO add your handling code here:
        AddPost AP = new AddPost('D');
        AP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        AP.setVisible(true);
    }//GEN-LAST:event_btnAddDiscussionActionPerformed

    private void btnAddSharingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSharingActionPerformed
        // TODO add your handling code here:
        AddPost AP = new AddPost('S');
        AP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        AP.setVisible(true);
    }//GEN-LAST:event_btnAddSharingActionPerformed

    private void SharingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SharingMouseClicked
        // TODO add your handling code here:
        offset = 0;
        limit = 1;
        panelPost.removeAll();
        panelPost.revalidate();
        panelPost.repaint();
        updatePost('S',offset,limit);
    }//GEN-LAST:event_SharingMouseClicked

    private void DisussionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisussionsMouseClicked
        // TODO add your handling code here:
        offset = 0;
        limit = 1;
        panelPost.removeAll();
        panelPost.revalidate();
        panelPost.repaint();
        updatePost('D',offset,limit);
    }//GEN-LAST:event_DisussionsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Disussions;
    private javax.swing.JLabel Sharing;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bio;
    private javax.swing.JButton btnAddDiscussion;
    private javax.swing.JButton btnAddSharing;
    private javax.swing.JButton btnEditProfile;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JPanel panelPost;
    private javax.swing.JLabel totalDiscussion;
    private javax.swing.JLabel totalPost;
    // End of variables declaration//GEN-END:variables
}
